import SwiftUI

enum MathItScreen: Hashable {
    case levelSelect
    case placeholder(Int)      // an unbuilt curriculum topic (carries its curriculum number)
    case levelOne
    case levelTwo
    case levelThree
    case levelFour
    case levelFive
    case levelSix
    case levelSeven
    case levelEight
    case levelNine
    case levelTen
    case levelEleven
    case levelTwelve
    case levelThirteen
    case levelFourteen
    case levelFifteen
    case levelSixteen
    case levelSeventeen
    case levelEighteen
    case levelNineteen
    case levelTwenty
    case levelTwentyOne
    case levelTwentyTwo
    case levelTwentyThree
    case levelTwentyFour
    case levelTwentyFive
    case levelTwentySix
    case levelTwentySeven
    case levelTwentyEight
    case levelTwentyNine
    case levelThirty
    case levelThirtyOne
    case levelThirtyTwo
    case levelThirtyThree
    case levelThirtyFour
    case levelThirtyFive
    case levelThirtySix
    case levelThirtySeven
    case levelThirtyEight
    case levelThirtyNine
    case levelForty
    case levelFortyOne
    case levelFortyTwo
    case levelFortyThree
    case levelFortyFour
    case levelFortyFive
    case levelFortySix
    case levelFortySeven
    case levelFortyEight
    case levelFortyNine
    case levelFifty
    case levelFiftyOne
    case levelFiftyTwo
    case levelFiftyThree
    case levelFiftyFour
    case levelFiftyFive
    case levelFiftySix
    case levelFiftySeven
    case levelFiftyEight
    case levelFiftyNine
    case levelSixty
    case levelSixtyOne
    case levelSixtyTwo
    case levelSixtyThree
    case levelSixtyFour
    case levelSixtyFive
    case levelSixtySix
    case levelSixtySeven
    case levelSixtyEight
    case levelSixtyNine
    case levelSeventy
    case levelSeventyOne
    case levelSeventyTwo
    case levelSeventyThree
    case levelSeventyFour
    case levelSeventyFive
    case levelSeventySix
    case levelSeventySeven
    case levelSeventyEight
    case levelSeventyNine
    case levelEighty
    case levelEightyOne
    case levelEightyTwo
    case levelEightyThree
    case levelEightyFour
    case levelEightyFive
    case levelEightySix
    case levelEightySeven
    case levelEightyEight
    case levelEightyNine
    case levelNinety
    case levelNinetyOne
    case levelNinetyTwo
    case levelNinetyThree
    case levelNinetyFour
    case levelNinetyFive
    case levelNinetySix
    case levelNinetySeven
    case levelNinetyEight
    case levelNinetyNine
    case levelOneHundred
    case levelOneHundredOne
    case levelOneHundredTwo
    case levelOneHundredThree
    case levelOneHundredFour
    case levelOneHundredFive
    case levelOneHundredSix
    case levelOneHundredSeven
    case levelOneHundredEight
    case levelOneHundredNine
    case levelOneHundredTen
    case levelOneHundredEleven
    case levelOneHundredTwelve
    case levelOneHundredThirteen
    case levelOneHundredFourteen
    case levelOneHundredFifteen
    case levelOneHundredSixteen
    case levelOneHundredSeventeen
    case levelOneHundredEighteen
    case levelOneHundredTwenty
    case levelOneHundredTwentyOne
    case levelOneHundredTwentyTwo
    case levelOneHundredTwentyThree
    case levelOneHundredTwentyFour
    case levelOneHundredTwentyFive
    case levelOneHundredTwentySix
    case levelOneHundredTwentySeven
    case levelOneHundredTwentyEight
    case levelOneHundredTwentyNine
    case levelOneHundredThirty
    case levelOneHundredThirtyOne
    case levelOneHundredThirtyTwo
    case levelOneHundredThirtyThree
    case levelOneHundredThirtyFour
    case levelOneHundredThirtyFive
    case levelOneHundredThirtySix
    case levelOneHundredThirtySeven
    case levelOneHundredThirtyEight
    case levelOneHundredThirtyNine
    case levelOneHundredForty
    case levelOneHundredFortyOne
    case levelOneHundredFortyThree
}

extension MathItScreen {
    /// App-wide gold accent — drives level title chrome, home/hint icons, overlays.
    var categoryAccent: Color { Color(red: 0.93, green: 0.78, blue: 0.40) }

    var isLevel: Bool {
        self != .levelSelect
    }
}
